### PR TITLE
Completed

### PR DESCRIPTION
**Pull request by jawadahmedtaj**
Completed,
Jawad Ahmed

### CODE REVIEW

**Comment by Neginysh** [comment]
Hey, 
Apk is not uploaded. Could you add it?

**Comment by jawadahmedtaj** [comment]
Hi,

I have pushed it to my repo. Do I have to create another pull request? Sorry about the mistake

**Comment by Neginysh** [comment]
No need for that. 
No problem.

**Comment by Neginysh** [comment]
Total point: 11
Looks good but there is no description or Readme file.

**Pull request closed without merging**
